
services:
- type: web
  name: Shadow-Cipher
  env: python
  repo: https://github.com/JaleneA/Project-Jinjago.git
  plan: free
  branch: main
  healthCheckPath: /healthcheck
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn wsgi:app"
  envVars:
  - fromGroup: shadow-cipher-settings
  - key: POSTGRES_URL
    fromDatabase:
      name: shadow-cipher-db
      property: host
  - key: POSTGRES_USER
    fromDatabase:
      name: shadow-cipher-db
      property: user
  - key: POSTGRES_PASSWORD
    fromDatabase:
      name: shadow-cipher-db
      property: password
  - key: POSTGRES_DB
    fromDatabase:
      name: shadow-cipher-db
      property: database 

envVarGroups:
- name: shadow-cipher-settings
  envVars:
  - key: ENV
    value: production
  - key: FLASK_APP
    value: wsgi.py

databases:
- name: shadow-cipher-db
  plan: free
  databaseName: mydb
